title                       : "fmralign tutorials"
author                      : Elizabeth DuPre
copyright                   : "2021"
logo                        : "../images/temp-logo.png"
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
bibtex_bibfiles:
  - references.bib

execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

html:
  favicon                   : ""  # A path to a favicon image
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false
  baseurl                   : ""  # Used for creating image previews and social links.
  use_multitoc_numbering    : false
  comments:
    hypothesis              : false
    utterances              : false

launch_buttons:
  notebook_interface        : classic  # Required for MyST content
  binderhub_url             : https://mybinder.org  # To update to NeuroLibre when ready
  thebe                     : false

repository:
  url                       : https://github.com/neurodatascience/fmralign-tutorials
  path_to_book              : "content"
  branch                    : main

sphinx:
  config:
    bibtex_reference_style: author_year
